apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and push docker image to ECR
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    steps:
    - name: Checkout code
      uses: cloudbees-io/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'temurin'
    - name: Maven Build
      uses: docker://maven:3-eclipse-temurin-17
      shell: sh
      run: |
       mvn clean package

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.27.0' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ssingh_aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.ssingh_aws_secret_access_key_id }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: cloudbees-io/configure-ecr-credentials@v1

    - name: Build, tag, and push docker image to Amazon ECR
      uses: cloudbees-io/kaniko@v1
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: saas-test
        IMAGE_TAG: latest
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG