apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and push docker image to ECR
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    steps:
    - name: Checkout code
      uses: cloudbees-io/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ssingh_aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.ssingh_aws_secret_access_key_id }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: cloudbees-io/configure-ecr-credentials@v1