apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and push docker image to ECR
on:
  push:
    branches:
      - "main"
jobs:
  build:
    steps:
    - name: Checkout code
      uses: cloudbees-io/checkout@v1
    - name: Maven Build
      uses: docker://maven:3-openjdk-11
      shell: sh
      run: |
       mvn clean package

    - name: Configure AWS Credentials
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.ssingh_aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.ssingh_aws_secret_access_key_id }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: cloudbees-io/configure-ecr-credentials@v1

    - name: Build, tag, and push docker image to Amazon ECR
      uses: cloudbees-io/kaniko@v1
      with:
       destination: 324005994172.dkr.ecr.us-east-1.amazonaws.com/saas-test
  
  deploy:
    needs:
      - build

    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
